### PR TITLE
Implement some missing string functions

### PR DESCRIPTION
**Pull request by th-otto**

### CODE REVIEW

**Comment by mikrosk** [comment]
Are you sure you have intended to base it on all of that PR merges and unrelated commits? A PR should be as small as possible, ideally rebased against master. If it's based on some other PR (for a good reason), noting something like "please merge PR #XY first" is enough.

Among others, there's commit 143c212703c which was explicitly rejected by @atic-atac in #15

**Comment by th-otto** [comment]
On Montag, 16. Oktober 2017 00:12:39 CEST Miro Kropacek wrote:
> Are you sure you have intended to base it on all of that PR merges and
> unrelated commits?

Not really, but it looks like it worked out this way. That strange list of 
commits appears because i merged my own local PR branches into master, for 
those that were already merged upstream.

>Among others, there's commit 143c212 which was explicitly rejected by @atic-
>atac in #15

Yes, i know. Actually, only the last 2 commits should been part of that PR. 
Any idea how to fix that now?

**Comment by mikrosk** [comment]
What I do before applying any PR is that I switch to master, pull, and start committing. For another PR I basically repeat the same process.

If/when I screw up, it's still very similar -- usually the mistake is to have master --> some branch --> maybe some other branch --> my code. So the most dumb-proof solution is just to switch to master, create something like branch_name_new, cherry pick given commits, switch to branch_name and reset its tip to branch_name_new and force push. That way the PR gets fixed without anyone knowing. ;-)

**Comment by th-otto** [comment]
On Montag, 16. Oktober 2017 00:52:32 CEST Miro Kropacek wrote:
> If/when I screw up, it's still very similar -- usually the mistake is to
> have master --> some branch --> maybe some other branch --> my code. So the
> most dumb-proof solution is just to switch to master, create something like
> branch_name_new, cherry pick given commits, switch to branch_name and reset
> its tip to branch_name_new and force push. That way the PR gets fixed
> without anyone knowing. ;-)

Thats sounds complicated, and also not very transparent ;) And you can only do 
a forced push as long as nobody else has already pulled the new objects.

In our case, the PR applies cleanly, although some of the referenced commits 
have already been merged into master. I think that is just because git sees 
the same commit ids in both master and this PR. So only problem is how to get 
rid of those commits as part of this PRs, otherwise its not very obvious what 
is new and what not.

**Comment by mikrosk** [comment]
> And you can only do a forced push as long as nobody else has already pulled the new objects.

But that doesn't matter -- it's your PR, your branch, your code. You can rebase it ten times and will be still OK because the reviewer get the look on your latest changes, not the mess which led there.

> So only problem is how to get rid of those commits as part of this PRs, otherwise its not very obvious what is new and what not.

See above, feel free to rewrite your branch's history, totally fine.

**Comment by th-otto** [comment]
Hmpf. That did not work. Now the commits are empty. New try.

**Comment by th-otto** [comment]
Ok, that looks better ;)

**Comment by mikrosk** [comment]
But still not there. :) For instance the PR-4 merge commit drags in the time zone stuff again. What do you want to have is a history in your PR-stringfuncs branch like this:

b9040d2478350a29080495a5f87a6a828cc60744
1de0b346a7a58f3a9c843069b9e4a49eaf266680
3a0a8459ac42804b890e0df4710615bbcd212db1 (master's tip)

Nothing else (unless there's a good reason to base it on some other PR).

**Comment by th-otto** [comment]
hm but i now have only
b9040d2
1de0b34
on that branch:

git rev-list --left-right master...PR-stringfuncs
>b9040d2478350a29080495a5f87a6a828cc60744
>1de0b346a7a58f3a9c843069b9e4a49eaf266680

**Comment by mikrosk** [comment]
... and did you push it? ;)
th-otto

**Comment by th-otto** [comment]
$git status
Your branch is up-to-date with 'origin/PR-stringfuncs'.

**Pull request closed without merging**
