### PR TITLE
Add executable flag to shell scripts

### PR DESCRIPTION
**Pull request by vinriviere**

### CODE REVIEW

**Comment by mikrosk** [comment]
I'm wondering -- why do you needs this? `.travis.yml` always calls scripts via `sh` or `.` so no problem here.

**Comment by vinriviere** [comment]
There is absolutely no need for that, just an obsessional fix as Git happily supports executable flags. Feel free to push this patch, or just ignore it. There will be no consequence.

**Comment by vinriviere** [comment]
BTW, if by design scripts must always be run with sh or .  then it would be safer to do the opposite of the patch proposed here. In other words remove the x flag on all scripts so they can never be run like executables.

**Comment by mikrosk** [comment]
You can run scripts directly with `./script.sh` from `.travis.yml` so it's purely cosmetic decision, yes. :)

**Pull request merged**
