### PR TITLE
Clean up assembler code to use % prefix for register names

### PR DESCRIPTION
**Pull request by th-otto**
This is necessary to be able to compile the sources using an
elf toolchain, and might also be necessary in the near future
when using newer assembler versions.

### CODE REVIEW

**Comment by mikrosk** [comment]
@th-otto you need to rebase your PR-registernames branch onto master to resolve the conflict.

**Comment by th-otto** [comment]
I think i will just redo the patch when time comes, too much hassle to resolve the conflicts all the time when files get changed by other commits.

But generally, i would really appreciate it if a decision could be made about that change in general (here, in the lib repo, and maybe also in the kernel). Without it, compiling it by newer versions of gcc, or elf toolchains, will stop to work.

**Comment by mikrosk** [comment]
I guess the nearing release is a good time to include this in the source tree. :)

**Comment by th-otto** [comment]
That has already been done ;) Did not use this PR since there were too many conflicts (it has rotten too long)

See https://github.com/freemint/mintlib/commit/fc1e15cc22a5b5e22d88e09e9026deb71a258619

**Pull request closed without merging**
