### PR TITLE
Rename constants in ctype.h, to avoid conflicts with c++ library

### PR DESCRIPTION
**Pull request by th-otto**

### CODE REVIEW

**Comment by mikrosk** [comment]
This is to avoid https://github.com/freemint/m68k-atari-mint-gcc/pull/3

**Comment by th-otto** [comment]
@mikrosk Sure. But i suggest to keep the patch to gcc (atleast until a new version of mintlib is released), it should not hurt, and you can use a release archive of mintlib, instead of relying on a git snapshot.

**Comment by mikrosk** [comment]
@th-otto I meant that as a side note, not questioning purpose of this patch. :) I agree this is the place to fix.

**Comment by mikrosk** [comment]
Interestingly, it seems that this patch broke compilation of the older gcc 4.6.4:

```
libtool: compile:  /home/mikro/atari/compilers/m68k-atari-mint-build/m68k-atari-mint-gcc-gcc-4_6-mint-m68000-cross-final/./gcc/xgcc -shared-libgcc -B/home/mikro/atari/compilers/m68k-atari-mint-build/m68k-atari-mint-gcc-gcc-4_6-mint-m68000-cross-final/./gcc -nostdinc++ -L/home/mikro/atari/compilers/m68k-atari-mint-build/m68k-atari-mint-gcc-gcc-4_6-mint-m68000-cross-final/m68k-atari-mint/libstdc++-v3/src -L/home/mikro/atari/compilers/m68k-atari-mint-build/m68k-atari-mint-gcc-gcc-4_6-mint-m68000-cross-final/m68k-atari-mint/libstdc++-v3/src/.libs -B/home/mikro/gnu-tools/m68000/m68k-atari-mint/bin/ -B/home/mikro/gnu-tools/m68000/m68k-atari-mint/lib/ -isystem /home/mikro/gnu-tools/m68000/m68k-atari-mint/include -isystem /home/mikro/gnu-tools/m68000/m68k-atari-mint/sys-include -I/home/mikro/atari/compilers/m68k-atari-mint-build/m68k-atari-mint-gcc-gcc-4_6-mint-m68000-cross-final/m68k-atari-mint/libstdc++-v3/include/m68k-atari-mint -I/home/mikro/atari/compilers/m68k-atari-mint-build/m68k-atari-mint-gcc-gcc-4_6-mint-m68000-cross-final/m68k-atari-mint/libstdc++-v3/include -I/home/mikro/atari/compilers/m68k-atari-mint-build/m68k-atari-mint-gcc-gcc-4_6-mint/libstdc++-v3/libsupc++ -fno-implicit-templates -Wall -Wextra -Wwrite-strings -Wcast-qual -fdiagnostics-show-location=once -D_GNU_SOURCE -O2 -fomit-frame-pointer -c ../../../../m68k-atari-mint-gcc-gcc-4_6-mint/libstdc++-v3/src/codecvt.cc -o codecvt.o
In file included from /home/mikro/atari/compilers/m68k-atari-mint-build/m68k-atari-mint-gcc-gcc-4_6-mint-m68000-cross-final/m68k-atari-mint/libstdc++-v3/include/bits/locale_facets.h:43:0,
                 from /home/mikro/atari/compilers/m68k-atari-mint-build/m68k-atari-mint-gcc-gcc-4_6-mint-m68000-cross-final/m68k-atari-mint/libstdc++-v3/include/locale:42,
                 from ../../../../m68k-atari-mint-gcc-gcc-4_6-mint/libstdc++-v3/src/codecvt.cc:25:
/home/mikro/atari/compilers/m68k-atari-mint-build/m68k-atari-mint-gcc-gcc-4_6-mint-m68000-cross-final/m68k-atari-mint/libstdc++-v3/include/m68k-atari-mint/bits/ctype_base.h:45:35: error: '_CTu' was not declared in this scope
/home/mikro/atari/compilers/m68k-atari-mint-build/m68k-atari-mint-gcc-gcc-4_6-mint-m68000-cross-final/m68k-atari-mint/libstdc++-v3/include/m68k-atari-mint/bits/ctype_base.h:46:32: error: '_CTl' was not declared in this scope
/home/mikro/atari/compilers/m68k-atari-mint-build/m68k-atari-mint-gcc-gcc-4_6-mint-m68000-cross-final/m68k-atari-mint/libstdc++-v3/include/m68k-atari-mint/bits/ctype_base.h:47:32: error: '_CTu' was not declared in this scope
/home/mikro/atari/compilers/m68k-atari-mint-build/m68k-atari-mint-gcc-gcc-4_6-mint-m68000-cross-final/m68k-atari-mint/libstdc++-v3/include/m68k-atari-mint/bits/ctype_base.h:47:39: error: '_CTl' was not declared in this scope
/home/mikro/atari/compilers/m68k-atari-mint-build/m68k-atari-mint-gcc-gcc-4_6-mint-m68000-cross-final/m68k-atari-mint/libstdc++-v3/include/m68k-atari-mint/bits/ctype_base.h:48:32: error: '_CTd' was not declared in this scope
/home/mikro/atari/compilers/m68k-atari-mint-build/m68k-atari-mint-gcc-gcc-4_6-mint-m68000-cross-final/m68k-atari-mint/libstdc++-v3/include/m68k-atari-mint/bits/ctype_base.h:49:33: error: '_CTx' was not declared in this scope
/home/mikro/atari/compilers/m68k-atari-mint-build/m68k-atari-mint-gcc-gcc-4_6-mint-m68000-cross-final/m68k-atari-mint/libstdc++-v3/include/m68k-atari-mint/bits/ctype_base.h:50:32: error: '_CTs' was not declared in this scope
/home/mikro/atari/compilers/m68k-atari-mint-build/m68k-atari-mint-gcc-gcc-4_6-mint-m68000-cross-final/m68k-atari-mint/libstdc++-v3/include/m68k-atari-mint/bits/ctype_base.h:51:32: error: '_CTP' was not declared in this scope
/home/mikro/atari/compilers/m68k-atari-mint-build/m68k-atari-mint-gcc-gcc-4_6-mint-m68000-cross-final/m68k-atari-mint/libstdc++-v3/include/m68k-atari-mint/bits/ctype_base.h:52:32: error: '_CTg' was not declared in this scope
/home/mikro/atari/compilers/m68k-atari-mint-build/m68k-atari-mint-gcc-gcc-4_6-mint-m68000-cross-final/m68k-atari-mint/libstdc++-v3/include/m68k-atari-mint/bits/ctype_base.h:53:32: error: '_CTc' was not declared in this scope
/home/mikro/atari/compilers/m68k-atari-mint-build/m68k-atari-mint-gcc-gcc-4_6-mint-m68000-cross-final/m68k-atari-mint/libstdc++-v3/include/m68k-atari-mint/bits/ctype_base.h:54:32: error: '_CTp' was not declared in this scope
/home/mikro/atari/compilers/m68k-atari-mint-build/m68k-atari-mint-gcc-gcc-4_6-mint-m68000-cross-final/m68k-atari-mint/libstdc++-v3/include/m68k-atari-mint/bits/ctype_base.h:55:32: error: '_CTd' was not declared in this scope
/home/mikro/atari/compilers/m68k-atari-mint-build/m68k-atari-mint-gcc-gcc-4_6-mint-m68000-cross-final/m68k-atari-mint/libstdc++-v3/include/m68k-atari-mint/bits/ctype_base.h:55:39: error: '_CTu' was not declared in this scope
/home/mikro/atari/compilers/m68k-atari-mint-build/m68k-atari-mint-gcc-gcc-4_6-mint-m68000-cross-final/m68k-atari-mint/libstdc++-v3/include/m68k-atari-mint/bits/ctype_base.h:55:46: error: '_CTl' was not declared in this scope
make[4]: *** [Makefile:608: codecvt.lo] Error 1
make[4]: Leaving directory '/home/mikro/atari/compilers/m68k-atari-mint-build/m68k-atari-mint-gcc-gcc-4_6-mint-m68000-cross-final/m68k-atari-mint/libstdc++-v3/src'
make[3]: *** [Makefile:469: all-recursive] Error 1
make[3]: Leaving directory '/home/mikro/atari/compilers/m68k-atari-mint-build/m68k-atari-mint-gcc-gcc-4_6-mint-m68000-cross-final/m68k-atari-mint/libstdc++-v3'
make[2]: *** [Makefile:377: all] Error 2
make[2]: Leaving directory '/home/mikro/atari/compilers/m68k-atari-mint-build/m68k-atari-mint-gcc-gcc-4_6-mint-m68000-cross-final/m68k-atari-mint/libstdc++-v3'
make[1]: *** [Makefile:12931: all-target-libstdc++-v3] Error 2
make[1]: Leaving directory '/home/mikro/atari/compilers/m68k-atari-mint-build/m68k-atari-mint-gcc-gcc-4_6-mint-m68000-cross-final'
make: *** [Makefile:895: all] Error 2

```

**Comment by th-otto** [comment]
Hm yes. That's because Vincents original patch for 4.6.4 uses a different approach for the locale files. You can use my patch from http://tho-otto.de/download/mint/gcc-4.6.4-mint-20170518.tar.bz2. Just don't apply the fastcall patch if you don't want it, otherwise it should be basically the same. And you may have to pass --with-pkgversion in the build script to get the output from gcc -v right, because it does not patch version.c

**Comment by mikrosk** [comment]
@vinriviere any idea what is better approach? Change your 4.6.4 or revert this one (at least for the time being, as we have a workaround in gcc 7.2 for this as well).

**Comment by th-otto** [comment]
Imho it's better solution to adjust the patch. Relying on internal constants of the c-library worked when that patch was created, but may break at any time. If the constants weren't needed for the macros, they would not even appear in that header file. OTOH, you only need to adjust the patch if you want to recompile the source yourself; afaik there are already binary packages available for all major platforms.

**Comment by vinriviere** [comment]
I'm lost here. This Pull Request is supposed to have been merged into master on 29 September, but the last commit in master history is from 11 June.
Regarding to the MiNTLib and this Pull Request, what are we waiting for ?

**Comment by mikrosk** [comment]
@vinriviere what do you mean? I can see it in mintlib's master on the 29th.

The current state is (from what I can see/remember) is that:
- gcc 4.6.4 needs adjusting as it depends on the internal constants which are removed by this PR (see https://github.com/freemint/mintlib/pull/21#issuecomment-334935667)
- gcc 7.2 can have https://github.com/freemint/m68k-atari-mint-gcc/pull/3 reverted as it's fixed on the mintlib side

**Pull request merged**
