### PR TITLE
Remove __MSHORT__, __PUREC__ and __SOZOBON__ code

### PR DESCRIPTION
**Pull request by mikrosk**
They are not supported for ages and just occupy space in source files.

As mentioned in the commit, I kept a few exceptions for cases that someone would like to use, say, `gcc -mshort` with `stdint.h` and his own libc for instance.

I've done it using `unifdef` tool, so it should be safe, I also manually inspected every change.

However another pair of eyes is always welcome.

### CODE REVIEW

**Comment by th-otto** [comment]
Sorry, but i absolutely disagree. Atleast mshort and Pure-C were both supported at some time in the past, and i would call it a regression that they don't work anymore. I would rather prefer try to make them working again, rather than to remove it.

**Comment by mikrosk** [comment]
You were right, they _were_ supported.

22 years ago Guido Flohr, the mintlib maintainer at that time, had removed it for good in commit ea4b69a9. Then there were two humble commits adding a few of the `__MSHORT__` defines in 2001 and 2002 respectively and then... your three commits in 2019 changing a few files (some of which I kept, by the way, I have no problem keeping also `byteswap.h` and `inttypes.h` changes, are they are harmless and possibly useful).

But thinking that someone will come and ressurect not only `-mshort` but also Pure C and others... that's just utopia.

**Comment by th-otto** [comment]
The commit from Guido Flohr only removed it from the build system, but not from any source files.

And its not that utopia to resurrect Pure-C for example (which implies -mshort, since Pure-C does not support 32bit ints). Some years ago i already started on that, and it was almost complete. I just did not integrate that yet, because (as you might expect) altogether the changes are quite massive, and by that time i had no motivation again to redo all the changes in smaller, better understandable commits.

BTW, for projects like hypview and magicmac i still use a set of header files that are modified for use by both Pure-C and mintlib.

Apart from that, i don't see any benefit of removing those ifdefs. As long as mintlib is not compiled with -mshort, the produced code will be the same. And even if the support is never completed, they still give a hint where problematic cases are, eg. in interfaces to the kernel.

**Comment by mikrosk** [comment]
> i don't see any benefit of removing those ifdefs. As long as mintlib is not compiled with -mshort, the produced code will be the same

Sure but it complicates things when a) reading/learning the code b) adding/changing things. With every new added function the code will rot more and more because nobody is testing it.

I'm lazy to go through mint list archives but I'm pretty sure that the `-mshort` support was dropped because it was too limiting and unmaintable and over the course of 20+ years there must be dozens of cases where the 16-bit API has been broken.

It's interesting that here you don't see any trouble with restoring missing pieces over 20 years but with xaaes-ozk where 'only' 10 years are involved you find it impossible. ;)

Don't get me wrong, I'm all for having mintlib with 16-bit support but not in state like this. I would argue that if someone like you wants to restore it, it's just matter of one revert, there shouldn't be any conflicts even in a more distant future.

**Comment by th-otto** [comment]
Don't get me wrong, but those ifdefs didn't bother you for 20 years. Why now?

There are a few places where they could be removed, eg. in md5-crypt.c if you keep the part using long ints instead. But by all means, i'm not in favour of accepting that PR as it is, just expecting to revert it in the future (which will surely be lots of work again if files have changed in the meantime).

**Comment by mikrosk** [comment]
Well, why - I was about to change bcopy.S and noticed that mess. It's always good to remove inactive parts of code, the less `#ifdef`s, the better. Especially if we are talking about code which hasn't been used in 20 years.

If you seriously mean your efforts to revive mintlib for mshort/purec all right then.

**Comment by th-otto** [comment]
> For example in XaAES c_message.c is totally unused and could be safely deleted.

XaAES is something completely different. I don't think that there is any code in mintlib that can be removed, because you'll never know who might be using it. 

> 4 months ago I tried to create my own distribution based on OPKG but I quickly discovered that a recent library is required to recompile programs without modifications.

I had no problems with it: https://tho-otto.de/crossmint.php#opkg The mint-specific patches are absolutely minimal

**Comment by mikrosk** [comment]
By all means @xdelatour, XaAES benefits from any cleanup you come up with. So feel free to submit patches for removing dead code, files, ifdefs etc... that code base virtually begs for cleanup and refactoring. So don't take this mintlib question as a general rule.

@th-otto I think Xavier meant that he wanted to automate also packages building (perhaps with some already premade recipes) and discovered that not all of them work with our mintlib out of the box.

But as an idea I support this, at some point I'd already made a bootstrap image based on Travis (R.I.P.) and aranym, where every package was rebuilt from scratch and the final stage was supposed to be `opkg`. I got pretty far: https://github.com/m68k-atari-mint/bootstrap but then Travis ended and I lost motivation. But it worked wonderfully.

**Comment by th-otto** [comment]
Yes, they might not work out of the box, but small patches are acceptable i think. If you look at linux distros, there are rarely packages that don't have small distro-specific patches, either. In the case of opkg, it was mainly for the missing mkdtemp() at that time, which i implemented when noticing it, so that patch isn't even needed anymore.

BTW, i also once started on building a "real" repo. You can view the result at http://tho-otto.de/download/rpm/ It uses a different approach, cross-compiling all the packages, but provides both libraries for cross-compilers as well as native ones.

**Comment by xdelatour** [comment]
Thank you both

Unfortunately I have no more time to spend on it for the moment and it's far from ready for production but here is what I had done thanks to your build scripts: https://kitfreemint.xdelatour.fr/

opkg is really very lightweight and the packages are very easy to create (a single archive which includes a control file and the file tree)

**Comment by mikrosk** [comment]
I agree, opkg is very nice. There even used to be a GEM frontend for it, I think it was implemented by Mark Duckworth.

Well, it seems all of us had more or less the same idea, I think we should cooperate / be more public about it next time to divide resources. :)

**Comment by mikrosk** [comment]
Ah, it is even publicly downloadable: http://storage.atari-source.org/atari/personal/gim/

**Comment by th-otto** [comment]
That seems to be an instant-messenger application, and has nothing to do with opkg.

**Comment by mikrosk** [comment]
Oh right, I forgot that he'd worked on that, too.

**Comment by th-otto** [comment]
But has there been a GUI for opkg? And are any sources available?

**Comment by th-otto** [comment]
Thanks. I even got it compiled after a few fixes, but it is as the readme says: the gem version does nothing except display a startup dialog, and for the commandline version only "info" works (and strangely reports that i have a locally installed package that is newer than the one from the sparemint server). Apart from that: the program is a whopping 4.5MB executable. Mainly because of curl  i guess, which in turn needs all the crypto stuff.

**Pull request closed without merging**
