### PR TITLE
Fix passing timezone structure in Tsettimeofday()/Tgettimeofday()

### PR DESCRIPTION
**Pull request by th-otto**

### CODE REVIEW

**Comment by atic-atac** [comment]
Why this patch, mintlib is only ever compiled for 32bit now, so ints are 32bit.

**Comment by th-otto** [comment]
> mintlib is only ever compiled for 32bit now, so ints are 32bit.

Maybe currently. But i think this is an unnecessary restriction. Gem programs like toswin2 and teradesk would be much more efficient if they could be compiled with -mshort. And in any case, long and int are different things, only because they happen to be the same size does not make them identical.

**Comment by atic-atac** [comment]
mintlib isn't compiled for mshort because of catching issues such as this. So toswin2/teradesk shouldn't be compiled against mintlib with mshort because it definitely will not work, even with this small fix. There are many many many more of these around. That's pretty much why Frank and the folks working on mintlib abadoned anything but 32bit.

**Comment by th-otto** [comment]
> There are many many many more of these around. 

Yes, i'm aware of that. Not really many, but quite a few. Of course those issues should be fixed, too.

**Comment by atic-atac** [comment]
So, I don't think your patch is the right then, it should change the original structure and not create a new one. Also if you want to support non-32bit mintlibs then the patch should be extensive and cover the entire library.

So feel free to carry on on your own branch until a much fuller fix is available, but I don't see any point in merging this to master.

**Pull request closed without merging**
