### PR TITLE
Several fixes, in separate commits

### PR DESCRIPTION
**Pull request by th-otto**
- Avoid optimization of malloc/memset to calloc in its own implementation
- Allow prefix for cross-tools to be overridden
- Fix for parallel makes
- Replace calls to deprecated bzero by memset
- Replace calls to deprecated bcopy by memcpy
- Move malloc-related definitions to separate file
- Fix long double math functions for coldfire
- Explicitly add -fno-omit-frame-pointer for sources that need it

### CODE REVIEW

**Comment by th-otto** [comment]
> Why -O1 ?

Should actually be -fno-builtin, or -fno-builtin-memset, but apparently the m68k backend does not recognize that as part of a pragma optimize.

**Comment by atic-atac** [comment]
Can you just pass it as CFLAGS option rather than embedding the the source file ?

**Comment by th-otto** [comment]
That might work too, but actually i'm not very fond of putting important flags hidden in some configuration file, when there are other possibilities. If you are concerned about reducing the optimization level, that function is short enough to produce the same code.

**Comment by atic-atac** [comment]
There's enough configuration using NOCFLAGS/CFLAGS going on that this is best placed in the same files so people can see it configured in the same way than buried in the C file.

**Comment by th-otto** [comment]
AFAIR, most of this stuff is for the files implementing profiling code. For these it is necessary, because specifying any options in the source file might be too late (there might have been calls to other library functions already from inline code of header files).
Also, since the build system does not use a configure script, it is not always possible to check from the Makefile, wether the compiler supports certain options.
But if you really insist, i just verified just gcc 4.6.4 supports -fno-builtin, and that using that option produces the intended result when using gcc 7.x, so if you really want, feel free to change that.

BTW if you wonder why this change is necessary at all:
without this, gcc 7.x might produce code like this:
___calloc:
        move.l 8(%sp),%d0
        moveq #1,%d1
        move.l %d1,8(%sp)
        move.l %d0,-(%sp)
        move.l 8(%sp),-(%sp)
        jsr ___mulsi3
        addq.l #8,%sp
        move.l %d0,4(%sp)
        jra ___calloc

**Comment by atic-atac** [comment]
But -O1 is wrong, and people could assume it's compiling without the right optimization levels.

If you can't express -fno-builtin-memset with #pragma then do it in CFLAGS properly.

**Comment by atic-atac** [comment]
I can't merge this without this change.

**Comment by atic-atac** [comment]
Oh, and it's not just profiling. -fwrapv is used to compile code correctly too.

**Comment by th-otto** [comment]
>I can't merge this without this change.

Done now. Just have to wait for travis to complete. Any other things to note about the other commits?

**Pull request merged**
